### ISSUE TITLE
V4L2_PIX_FMT_Y16 support

### ISSUE THREAD

**Issue by mattrei** [wedesoft/hornetseye-v4l2#10]
Hi,

I want to use my depth camera with your lib, however the output of this UVC cam is in the V4L2_PIX_FMT_Y16 (16 Bit grayscale) format (http://linuxtv.org/downloads/v4l-dvb-apis/V4L2-PIX-FMT-Y16.html)

I am not so familiar with C so I ask you where would I need to dig in to give support for this colorspace? 

Thanks for your support,
Matthias

**Comment by wedesoft** [comment]
Are you getting the error message "Conversion for V4L2 colorspace ... not implemented yet"? You could just try creating a frame with typecode "USINT" [where the error is thrown](https://github.com/wedesoft/hornetseye-v4l2/blob/master/ext/v4l2input.cc#L140).

**Comment by mattrei** [comment]
Hi,
yes it outputs a picture, see yourself, however its not "right". I really have now clue about image processing tbh, however I think there is a problem with signed and unsigned datatype. Normally what is near should be white, what is far away should be dark.
See: 
![2016-01-05-091422_1920x1080_scrot](https://cloud.githubusercontent.com/assets/379706/12110494/f391d2bc-b38c-11e5-8e7c-d8809cb4bd94.png)
compared to what the OpenNI library outputs me
![2016-01-05-091703_1920x1080_scrot](https://cloud.githubusercontent.com/assets/379706/12110523/3e914a18-b38d-11e5-861b-c20242dcc1c8.png)

(Where does the USINT come from, could not find that declaration in your hornetseye-frame lib)

(BTW I am using the Asus Xtion with the uvc-Kernel-module:  https://github.com/xqms/xtion)

Appreciate your help very much

**Comment by wedesoft** [comment]
On January 5, 2016 8:19:18 AM GMT, Matthias Treitler <notifications@github.com> wrote:
>Hi,
>yes it outputs a picture, see yourself, however its not "right". I
>really have now clue about image processing tbh, however I think there
>is a problem with signed and unsigned datatype. Normally what is near
>should be white, what is far away should be dark.
>See: 
>![2016-01-05-091422_1920x1080_scrot](https://cloud.githubusercontent.com/assets/379706/12110494/f391d2bc-b38c-11e5-8e7c-d8809cb4bd94.png)
>compared to what the OpenNI library outputs me
>![2016-01-05-091703_1920x1080_scrot](https://cloud.githubusercontent.com/assets/379706/12110523/3e914a18-b38d-11e5-861b-c20242dcc1c8.png)
>
>(Where does the USINT come from, could not find that declaration in
>your hornetseye-frame lib)
>
>(BTW I am using the Asus Xtion with the uvc-Kernel-module: 
>https://github.com/xqms/xtion)
>
>Appreciate your help very much
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/hornetseye-v4l2/issues/10#issuecomment-168932194

The graphics display only has 8 bit. So you need to normalise the image. The Ruby code would be something like: X11Display.show { input.read.normalise }
-- 
Jan Wedekind
http://www.wedesoft.de/

**Comment by mattrei** [comment]
many thanks :+1: 

Shall I create a pull request?

best

**Comment by wedesoft** [comment]
On January 5, 2016 11:31:23 AM GMT, Matthias Treitler <notifications@github.com> wrote:
>many thanks :+1: 
>
>Shall I create a pull request?
>
>best
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/hornetseye-v4l2/issues/10#issuecomment-168976969

Brilliant. Yes, please create a pull request.
BTW. You can also normalise and invert in one step: X11Display.show { input.read.normalise 255..0 }
-- 
Jan Wedekind
http://www.wedesoft.de/
