### ISSUE TITLE
warning from camera read

### ISSUE THREAD

**Issue by Pepan** [wedesoft/hornetseye-v4l2#9]
[swscaler @ 0x7f4410009da0] Warning: data is not aligned! This can lead to a speedloss

example:
```ruby
  camera = V4L2Input.new do |modes|
    modes[0]
  end

# wait for sync
  puts 'wait for sync'
  3.times do |i|
    sleep 0.3
    img = camera.read
  end
  puts 'start'

  sleep 1
  img = camera.read
  file = "photos/photo_#{Time.now.to_i}.jpg"
  img.to_ubytergb.save_ubytergb '../web/public/'+file

  camera.close
  puts 'end'
```

**Comment by wedesoft** [comment]
Hi,
I just added memory alignment to malloc (version 1.5.0) and I changed hornetseye-frame (version 1.1.0) to make use of it. I hope this will fix the performance issue.

**Comment by Pepan** [comment]
It works. Thank you!

**Comment by wedesoft** [comment]
Ok, thanks for letting me know. Had to set the unused pointers to zero because libswscale checks every pointer whether it is aligned (even if it is not in use).
